### ISSUE TITLE
"pip install" does not work - sensirion requirement missing

### ISSUE THREAD

**Issue by marlesus** [Sensirion/python-i2c-sf06-lf#1]
Hello,

I tried to install the sensirion_i2c_sf06_lf according to the instructions here: https://sensirion.github.io/python-i2c-sf06-lf/installation.html , but I cannot succeed to install it, because I keep getting the error message in the picture below:
![image](https://user-images.githubusercontent.com/99021620/162149344-6057587c-6d9b-4222-adc9-73a078b66767.png)

Could you please help me?
I need to be able to control (start measurements, save and extract data etc.) the SLF3S-1300F sensor from python, using the SCC1-USB cable. Do you have a working example for this?

Thank you for your time and help!

Best regards,
Paul

**Comment by psachs** [comment]
Hi Paul,

Thanks for pointing that out. Looks like we did not release the sensirion-driver-support-types library on pypi and github.
We will fix that asap and I let you know once its done

**Comment by psachs** [comment]
The missing dependency should now be deployed on pypi.
