### ISSUE TITLE
Micropython Implementation of Python-i2c-sf06-If

### ISSUE THREAD

**Issue by TDoggin** [Sensirion/python-i2c-sf06-lf#3]
I have been trying to use the SLF3S-1300F Liquid Flow Sensor with an ESP32-S2 over I2C, but have been experiencing alot of issues with getting it to communicate on the bus when i stubbled across this python implementation. Has this been ported or able to be ported easily to Micropython? I realize that this is off topic but thought i would ask

**Comment by quentin-cy** [comment]
Hello @TDoggin ,

Unfortunately we do no have any MicroPython implementation available. I will however report your interest into having MicroPython drivers. Hopefully we will be able to provide them in the future. 
When it comes to porting it yourself, I do not see any obvious issue. MicroPython even includes some I2C tools that will greatly simplify the work.

If Arduino is an option for your project, we have the [Arduino driver for SF06 LF](https://github.com/Sensirion/arduino-i2c-sf06-lf). Using the given example you should not have any issues communicating with the sensor.

Feel free to reach out if you need further help.
